// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

package com.chuhui.customerpc.convention.transfer;

public final class Protocols {
  private Protocols() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_chuhui_customerpc_convention_transfer_URL_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_chuhui_customerpc_convention_transfer_URL_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\017Protocols.proto\022)com.chuhui.customerpc" +
      ".convention.transfer\"%\n\003URL\022\020\n\010hostNmae\030" +
      "\001 \001(\t\022\014\n\004port\030\002 \001(\005B-\n)com.chuhui.custom" +
      "erpc.convention.transferP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_chuhui_customerpc_convention_transfer_URL_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_chuhui_customerpc_convention_transfer_URL_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_chuhui_customerpc_convention_transfer_URL_descriptor,
        new String[] { "HostNmae", "Port", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
