// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Protocols.proto

package com.chuhui.customerpc.convention.transfer;

public interface URLOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.chuhui.customerpc.convention.transfer.URL)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string hostNmae = 1;</code>
   */
  String getHostNmae();
  /**
   * <code>string hostNmae = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostNmaeBytes();

  /**
   * <code>int32 port = 2;</code>
   */
  int getPort();
}
